export const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  IS_PLAYING_SONG: "IS_PLAYING_SONG",
  SET_ALBUM: "SET_ALBUM",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  SET_RECENT_SONG: "SET_RECENT_SONG",
  REMOVE_PLAYLIST: "REMOVE_PLAYLIST",
  REMOVE_RECENT_SONG: "REMOVE_PRECENT_SONG",
  SEARCH : 'SEARCH',
};
